### ISSUE TITLE
Empty presAbs_?.txt, maxREPIN_?.txt

### ISSUE THREAD

**Issue by CFGrote** [mpievolbio-scicomp/rarefan#18]
This run http://rarefan.evolbio.mpg.de/results?run_id=f7s42mg9 is a rerun of b2ecb95l which was originally submitted by Ref. 2. She comments: 

` I don’t understand why certain maxREPIN_[0-5] files are empty? Could the reason be added to the output file description? Goes the same for presAbs_[0-5].txt files`

Indeed, [presAbs_1.txt](http://rarefan.evolbio.mpg.de/files/f7s42mg9/out/presAbs_1.txt),  [presAbs_2.txt](http://rarefan.evolbio.mpg.de/files/f7s42mg9/out/presAbs_2.txt), have no data (only the header row) and [maxREPIN_1.txt](http://rarefan.evolbio.mpg.de/files/f7s42mg9/out/maxREPIN_1.txt) and [maxREPIN_2.txt](http://rarefan.evolbio.mpg.de/files/f7s42mg9/out/maxREPIN_2.txt) are completely empty.

We should explain why these files are empty in the documentation, in the paper, and in a README file accompanying the output data (TBD)

**Comment by fredeBio** [comment]
I think it is a parsing issue. I thought we fixed this ages ago, but I guess we did not.

----- Original Message -----

**Comment by CFGrote** [comment]
So everything is correct

The RAYT that was identified does not seem to be associated to any of the REPIN groups

 the plot still shows REPINS, just that these are not associated to the identified RAYT

RAYTs should always be associated to REPINs but not the other way around. However, if you do not find an association it does not mean there is none

have to modify the REPIN association file.
